### ISSUE TITLE
Error deploying emr_launch_function/

### ISSUE THREAD

**Issue by sterlaydy** [awslabs/aws-emr-launch#1]
Following the launch examples raises a error when deploying  emr_launch_function:

jsii.errors.JavaScriptError: 
  Error: ENOENT: no such file or directory, stat '/home/ec2-user/environment/aws-emr-launch/aws_emr_launch/lambda_sources/layers/emr_config_utils'

**Comment by chamcca** [comment]
Deploying the examples requires installing the Lambda Layer packages. The README for the examples doesn't mention this. To install the Lambda Layer packages, activate the virtual environment, then from the top-level aws-emr-launch directory:

```bash
pip install -r requirements-lambda-layer.txt \
--target=aws_emr_launch/lambda_sources/layers/emr_config_utils/python/lib/python3.7/site-packages/
```

**Comment by sterlaydy** [comment]
Solved. Thank you. But it raises another one:

EmrLaunchFunctionStack

Resource must be in ARN format or "*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID:)

**Comment by chamcca** [comment]
I suspect this is because one of the environment variables for the SecretsManager Secrets wasn't an ARN. I was able to reproduce the error using only a Secret name. 

I recommend pulling the latest version. We have updated the examples to include an environment_stack to prepare the environment and eliminate the need to set the environment variables.

**Comment by diogonando** [comment]
Hi, I was trying run the examples and I had the same problem. 
I solved it with two actions:
- I corrected some problems with my virtualenv, there was a python alias in my .bashrc that was point to a other path
- I remove the aws-emr-launch package from pypi, version 1.3.1, and I installed from source.
