### ISSUE TITLE
[BUG] - RunJobFlowServiceRole missing permissions to create AWSServiceRoleForEMRCleanup role 

### ISSUE THREAD

**Issue by awsjputro** [awslabs/aws-emr-launch#21]
**Describe the bug**
The package does not work in a brand new AWS account (or an account that has never used EMR before), because RunJobFlowServiceRole created is missing permissions to create AWSServiceRoleForEMRCleanup role.
Reference: https://docs.aws.amazon.com/emr/latest/ManagementGuide/using-service-linked-roles.html 

**To Reproduce**
1. Get a new AWS account or use an AWS account where AWSServiceRoleForEMRCleanup role doesn't exist yet (has never used EMR before)
2. Create a CDK app that will launch an EMR cluster using this package
3. Launch cluster will fail with the error message: "Terminated with errorsService-linked role 'AWSServiceRoleForEMRCleanup' for EMR is required. Please create this role directly or add permission to create it in your IAM entity."
PS: The screen shot is attached.

**Expected behavior**
AWSServiceRoleForEMRCleanup role should be automatically created if RunJobFlowServiceRole has sufficient permissions.
[](url)
**Screenshots**

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
![EMR-–-AWS-Console](https://user-images.githubusercontent.com/107270958/210888454-55cfaaed-eabd-40a5-b224-7b0420986459.png)

**Comment by awsjputro** [comment]
Is there a way for me to manually attach custom policy to the created RunJobFlowServiceRole* role?

**Comment by chamcca** [comment]
creation of the service linked role is a one-time setup that needs to occur in each account in order to use the AWSServiceRoleForEMRCleanup. rather than attaching a policy it is recommended that you manually create the service linked role. this is most easily done with the AWS CLI:
```
aws iam create-service-linked-role --aws-service-name elasticmapreduce.amazonaws.com
```

**Comment by awsjputro** [comment]
Yeah, you're right and I agree. Thank you.
